// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqKkQVb-nu1gttshWttF9nhUlLG02mFcs',
    appId: '1:863742835429:web:32e6fa1ba0c64a2625720c',
    messagingSenderId: '863742835429',
    projectId: 'usuarios-ff1aa',
    authDomain: 'usuarios-ff1aa.firebaseapp.com',
    databaseURL: 'https://usuarios-ff1aa-default-rtdb.firebaseio.com',
    storageBucket: 'usuarios-ff1aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2C4nrq4lGs6E-L4YtUJ3bLpBmuJLsp3A',
    appId: '1:863742835429:android:1f13e8f02e9dbe9c25720c',
    messagingSenderId: '863742835429',
    projectId: 'usuarios-ff1aa',
    databaseURL: 'https://usuarios-ff1aa-default-rtdb.firebaseio.com',
    storageBucket: 'usuarios-ff1aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc3WDTqKBWK7EaznRFxxQBhateaF3Pbx8',
    appId: '1:863742835429:ios:3816634e2d12174425720c',
    messagingSenderId: '863742835429',
    projectId: 'usuarios-ff1aa',
    databaseURL: 'https://usuarios-ff1aa-default-rtdb.firebaseio.com',
    storageBucket: 'usuarios-ff1aa.firebasestorage.app',
    iosBundleId: 'com.example.pruebaApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc3WDTqKBWK7EaznRFxxQBhateaF3Pbx8',
    appId: '1:863742835429:ios:3816634e2d12174425720c',
    messagingSenderId: '863742835429',
    projectId: 'usuarios-ff1aa',
    databaseURL: 'https://usuarios-ff1aa-default-rtdb.firebaseio.com',
    storageBucket: 'usuarios-ff1aa.firebasestorage.app',
    iosBundleId: 'com.example.pruebaApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqKkQVb-nu1gttshWttF9nhUlLG02mFcs',
    appId: '1:863742835429:web:934560a6595f387425720c',
    messagingSenderId: '863742835429',
    projectId: 'usuarios-ff1aa',
    authDomain: 'usuarios-ff1aa.firebaseapp.com',
    databaseURL: 'https://usuarios-ff1aa-default-rtdb.firebaseio.com',
    storageBucket: 'usuarios-ff1aa.firebasestorage.app',
  );
}
