// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbRSVmx36ra_qPlPw-_O1vJjw_zFX15C0',
    appId: '1:132951764258:web:0f93484fa6d1061bb3897b',
    messagingSenderId: '132951764258',
    projectId: 'iot-calidad-agua-3165b',
    authDomain: 'iot-calidad-agua-3165b.firebaseapp.com',
    storageBucket: 'iot-calidad-agua-3165b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSkHVQICQ712enYj5qWnOadcjOzA4Nwvg',
    appId: '1:132951764258:android:51ab66c1790b68f2b3897b',
    messagingSenderId: '132951764258',
    projectId: 'iot-calidad-agua-3165b',
    storageBucket: 'iot-calidad-agua-3165b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvdVt0e0VCwaF6bvPwsZ7y6tkaZ1wj6lI',
    appId: '1:132951764258:ios:8a272ac965266b7cb3897b',
    messagingSenderId: '132951764258',
    projectId: 'iot-calidad-agua-3165b',
    storageBucket: 'iot-calidad-agua-3165b.firebasestorage.app',
    iosBundleId: 'com.example.pruebaApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvdVt0e0VCwaF6bvPwsZ7y6tkaZ1wj6lI',
    appId: '1:132951764258:ios:8a272ac965266b7cb3897b',
    messagingSenderId: '132951764258',
    projectId: 'iot-calidad-agua-3165b',
    storageBucket: 'iot-calidad-agua-3165b.firebasestorage.app',
    iosBundleId: 'com.example.pruebaApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbRSVmx36ra_qPlPw-_O1vJjw_zFX15C0',
    appId: '1:132951764258:web:e7fc8100e21ea96bb3897b',
    messagingSenderId: '132951764258',
    projectId: 'iot-calidad-agua-3165b',
    authDomain: 'iot-calidad-agua-3165b.firebaseapp.com',
    storageBucket: 'iot-calidad-agua-3165b.firebasestorage.app',
  );

}